### ISSUE TITLE
獣害情報一覧APIを作成する

### ISSUE THREAD

**Issue by gunsow911** [gunsow911/ono_hackathon_saru#17]
# 概要
獣害情報一覧APIを作成してください。

URLは以下のようになります。
`GET: /api/console/matters`

また、Controllerは、以下のアクションを利用してください。
`App/UseCases/Matter/ListAction`

**Comment by greenthinktank** [comment]
できるかわかりませんが、ちょっとこちらをlaravelの学習がてらやってみようと思います！
devブランチからfeature/17を作って作業する感じで大丈夫でしょうか？
