### ISSUE TITLE
獣害の位置情報の記録先をスプレッドシートからデータベースに変更する

### ISSUE THREAD

**Issue by gunsow911** [gunsow911/ono_hackathon_saru#3]
# 概要
獣害の位置情報の記録先をスプレッドシートからデータベースに変更してください。
スプレッドシートの記録の読み込みは一般的に遅く、クエリを利用した検索ができず非効率です。

**Comment by nobufumi-tego** [comment]
BigQueryが推しです。
https://cloud.google.com/bigquery?hl=ja

**Comment by gunsow911** [comment]
ありがとうございます！あまりBigQueryのことを把握していなかったので、調べてみました。
いくつか懸念点があります。

・ORM(Object Relational Mapping)がサポートされてなさそう？
SQLを直接触るのは、かなりリスキーです。どのORMでも良いのですが、BigQueryのサポートがあると嬉しいです。

・ユニットテスト環境が無い
ローカルのみで料金を気にせずテストを行いたいです。
ローカルで完結できる仕組みがあると嬉しいです。

BigQueryに関しては分析用のものかな？というのが全体的な印象なので、例えば、
mysqlで作って、そのデータをBigQueryと同期するというのはどうでしょうか？
(料金的にどうなるかは一度シミュレーションしたほうが良さげです。)
https://cloud.google.com/datastream-for-bigquery?hl=ja

**Comment by nobufumi-tego** [comment]
私がORM使ったことがないので、今使ってるのは SQLで直接インサートしてます。
Google Cloud Functiions からの処理なら個人的にはORMなしでシンプルにSQL直でいいかと思ったりします。
ユニットテストも確かにです。こっちも調査してみますが、あまり期待できないかも。
ローカルのシュミレータがあるって情報見つけました。試してはないですが・・・。
https://qiita.com/Hisaaki-Kato/items/7b57e53058d80b71c8c0
RDBMで直近のデータを格納して、BQへ吐き出すのはありですね。
基本、BQはそういった使い方がメインと思います。
私が直接使ってるのがレアケースだと思います。
