### ISSUE TITLE
GoogleCloudFunctionsを利用したバックエンド環境を構築する

### ISSUE THREAD

**Issue by gunsow911** [gunsow911/ono_hackathon_saru#4]
# 概要 
GoogleCloudFunctionsを利用したバックエンド環境を構築します。
バックエンドのサーバレスで開発を行います。
また、開発言語はフロントエンドのNext.jsに合わせた、Typescript(Node.js)で行います。

**Comment by nobufumi-tego** [comment]
Google BigQuery に GoogleFunctions からデータを入れるがいいと思います。
個人的に気象情報収集に使ってます。Insert で使ってます。
Selectも行けそうですね。また相談させてください。
BQ
https://cloud.google.com/bigquery?hl=ja
Functions
https://cloud.google.com/functions?hl=ja

**Comment by gunsow911** [comment]
ありがとうございます！
#3にも関連しますが、私が、まだ若干BigQueryの勘所がわかっていない感じです。。。
色々触ってみます👍

**Comment by gunsow911** [comment]
良い資料を見つけた！
https://gatch.site/cloud-functions-local/

**Comment by nobufumi-tego** [comment]
資料ありがとうございます(^^v。

**Comment by gunsow911** [comment]
バックエンドの開発に関してはLaravelを使います。
