### ISSUE TITLE
ユーザ編集画面を作成する

### ISSUE THREAD

**Issue by gunsow911** [gunsow911/ono_hackathon_saru#42]
# 概要
ユーザ編集画面を作成してください。
フロントエンドのURLは以下になります。
`/console/users/{user}`

また、APIを利用して、ユーザが実際に更新および削除できるようにしてください。

- [ ] 更新
- [ ] 削除

**Comment by greenthinktank** [comment]
@gunsow911 
確認なのですが、ユーザーの作成・更新・削除ができるのは管理者だけという認識で合っておりますでしょうか？

とりあえず管理者だけがユーザーに関する操作ができるという形で、使う人が増えてきたら、管理者以外も作成できるようにする、というような想定でしょうか？

**Comment by gunsow911** [comment]
今のところ管理者のみユーザ作成ができるようにしています
今の運用としては、その他の人にユーザを作成してもらう予定はありません

**Comment by greenthinktank** [comment]
> 今のところ管理者のみユーザ作成ができるようにしています 今の運用としては、その他の人にユーザを作成してもらう予定はありません

ありがとうございます！
