### ISSUE TITLE
詳細ページの削除に確認ダイアログを作成する

### ISSUE THREAD

**Issue by gunsow911** [gunsow911/ono_hackathon_saru#56]
# 概要
ユーザに確認を求めるための確認ダイアログを作成してください。

**Comment by greenthinktank** [comment]
@gunsow911 
これは結構むずかしいでしょうか？
ダイアローグの部分をコピペで持ってきて加工して使えるようにしてみます。

とりあえず、情報詳細表示画面（ユーザー情報と獣害情報両方）で削除する場合に「本当に削除してもよいですか？」というメッセージを出せるようにしてみようと思います！

情報一覧の削除でモーダルを出すのはまた別issueとしたいと思います。
