### ISSUE TITLE
情報一覧で情報を削除する時にmodal windowで確認画面を出す

### ISSUE THREAD

**Issue by greenthinktank** [gunsow911/ono_hackathon_saru#74]
#56 から分離させたissueです。

### **#一覧表で削除する仕様どうする問題**

ちょっと思ったのは、この一覧の詳細ボタンの横に、削除ボタンがあるのがいいのかどうかというのが気になりました。

あくまで主観的な印象でしかありませんが、よくあるのは、チェックを入れたものを一括で削除するというような「チェック入れる」→「一括削除ボタンを押す」という二段構えが多いなあと。

今のままで行くのか、削除ボタンの仕様を変えるのか、どちらが適切なのかというのが気になっています。次回のミーティングで話すor実際に現場に使ってもらってから決めるでも良さそうとは思います。

### **#現在の画面**
![スクリーンショット 2023-05-06 11 49 34](https://user-images.githubusercontent.com/43633900/236596700-e12663d8-9fc9-402c-a93a-19ca7661eb04.png)

### **#難しいかもポイント**
モーダルの表示非表示の「const [visible, setVisible] = useState(false)」の状態が一覧表だとその行数個存在する形になることがややこしくなる原因？

### **#タスク** 
- [ ] ユーザー情報一覧
- [ ] 獣害情報一覧

**Comment by gunsow911** [comment]
おっしゃるとおりですね…！
一覧を選択して一気に削除のほうが、用途としてはあっていると思います。
(個別で削除したい場合は詳細 -> 削除で行けますので)

**Comment by greenthinktank** [comment]
> おっしゃるとおりですね…！ 一覧を選択して一気に削除のほうが、用途としてはあっていると思います。 (個別で削除したい場合は詳細 -> 削除で行けますので)

確認ありがとうございます。となるとやはりチェックボックスの新設＋一覧での削除時のモーダル出現という作業になりそうですね。

**Comment by greenthinktank** [comment]
このissueは #83 の方法に実装を変更したため、不要になりました。
